config/routes.rb
Rails.application.routes.draw do
resources :showings, only: [:new, :create]
resources :movies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/showing.rb
class Showing < ApplicationRecord
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:show,:edit,:update,:destroy]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create 
    @movie = Movie.create(allowed_params)
      redirect_to movies_path
  end

  def show
    @showings = Showing.order(:time).select{|showing| showing.movie== @movie}
  end

  def edit 
  end

  def update
    @movie.update(allowed_params)
    redirect_to movie_path(@movie)
  end

  def destroy 
    @movie.destroy
    redirect_to movies_path
  end



  private 

  def allowed_params
    params.require(:movie).permit(:title, :release_date, :in_theaters)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end
end

app/controllers/showings_controller.rb
class ShowingsController < ApplicationController
  def new
    @showing = Showing.new
  end

  def create 
    @showing = Showing.create(allowed_params)
    redirect_to movie_path(@showing.movie_id)
  end

  private 

def allowed_params
  params.require(:showing).permit(:time,:movie_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/showings_helper.rb
module ShowingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h2> Edit <%= @movie.title %> </h2>

<%= form_for @movie do |f| %>
<%= f.label :title %> 
<%= f.text_field :title %>
<%= f.label :release_date %> 
<%= f.number_field :release_date %>
<%= f.label :in_theaters %> 
<%= f.check_box :in_theaters %>
<%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<h1> Movies </h1>

<ul>
    <% @movies.each do |movie| %>
    <li>
        <h2><%= movie.title %></h2>
        <p>Release Date: <%= movie.release_date %></p>
            <% if movie.in_theaters %>
                <p>In theatres: Yes</p>
            <% else %>
                <p>In theatres: No</p>
            <% end %>
    </li>
    <%end%>
</ul>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>


<%= form_for @movie do |f| %>
<%= f.label :title %> 
<%= f.text_field :title %>
<%= f.label :release_date %> 
<%= f.number_field :release_date %>
<%= f.label :in_theaters %> 
<%= f.check_box :in_theaters %>
<%= f.submit %>
<% end %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<h3>Showings</h3>
<% @showings.each do |showing| %>
<p><%= showing.time %>  </p>
<%end%>

<br>
<%= link_to  "Edit Movie", edit_movie_path(@movie) %>
<%= link_to  "Add Showing", new_showing_path %>
<%= button_to "Delete Movie", @movie,  method: :delete %>

app/views/showings/new.html.erb
<%= form_for @showing do |f| %>
<%= f.label :time %> 
<%= f.number_field :time %>
<%= f.label :movie %>
<%= f.collection_select :movie_id, Movie.all, :id, :title, prompt: true %>
<%= f.submit %>
<% end %>